### ISSUE TITLE
could not find function "mixed_model_using_splits"

### ISSUE THREAD

**Issue by keval-hyperspace** [mladenjovanovic/shorts#8]
could not find function "mixed_model_using_splits"
I try to run this script using cmd but the error is accord

**Comment by keval-hyperspace** [comment]
I try to run this script using cmd but the error is accord

**Comment by mladenjovanovic** [comment]
Please refer to this "manual" for the usage:
http://osf.io/4jw62/

Scripts can be found in the R directory: https://github.com/mladenjovanovic/shorts/blob/master/R/mixed_model_using_splits.R
